language: ruby

rvm:
  - 2.6.0

services:
  - postgresql

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

env:
  global:
  - PGPORT=5433

before_script:
  - cp config/database.yml.travis config/database.yml 

script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
